version: '3.9'

services:
  resume:
    image: resume
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume
    restart: unless-stopped
    ports:
      - "7070:8080"
    networks:
      - resume

networks:
  resume:
    name: resume
    driver: bridge